name: Test CI/CD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, ${{ github.actor }}. You just ran a GitHub Action!"
